### ISSUE TITLE
Guide Updates

### ISSUE THREAD

**Issue by Jskobos** [linode/docs#1393]
The following guides should be added to upcoming iterations for updates. Each is frequently used, has not seen significant updates in several years, and/or has formatting and style issues that do not match current house style.

- [x] email/running-a-mail-server/ #1424 
- [x] tools-reference/tools/use-killall-and-kill-to-stop-processes/ #1411 
- [x] tools-reference/tools/modify-file-permissions-with-chmod/ #1449 
- [x] security/ssl/install-lets-encrypt-to-create-ssl-certificates/ (not old, but should be updated to reference CertBot). #1536 
- [x] tools-reference/tools/manipulate-lists-with-sort-and-uniq/ #1509 
- [x] databases/oracle/securely-administer-oracle-xe-with-an-ssh-tunnel/ (deprecate?) #1409

**Comment by kcraig34** [comment]
Putting them into cards for today's powerpointing. 
Thanks, @Jskobos

**Comment by GuessWhoSamFoo** [comment]
Resolved
